src/java/managedBean/CursoBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedBean;

import entidades.Curso;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;
import servicios.CursoFacadeLocal;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletResponse;
import org.primefaces.model.UploadedFile;

@Named(value = "cursoBean")
@RequestScoped
public class CursoBean {

    @EJB
    private CursoFacadeLocal cursoFacade;

    private UploadedFile file;
    private String msj;
    private Curso curso;

    public CursoBean() {
    }

    public Curso getCurso() {
        return curso;
    }

    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    public UploadedFile getFile() {
        return file;
    }

    public void setFile(UploadedFile file) {
        this.file = file;
    }

    @PostConstruct
    public void init() {
        this.curso = new Curso();
    }

    public void insert() {

        try {
            //Logica para subir imagen
            InputStream input = file.getInputstream();
            ByteArrayOutputStream output = new ByteArrayOutputStream();
            byte[] buffer = new byte[1024];

            for (int length = 0; (length = input.read(buffer)) > 0;) {
                output.write(buffer, 0, length);

            }
            curso.setFoto(output.toByteArray());//Seteamos la imagen en la entidad curso
            cursoFacade.create(curso); //Se envia como parametro la entidad curso en el metodo del EJB
            this.curso = new Curso();
            this.msj = "Curso Insertado Correctamente";
        } catch (Exception e) {
            e.printStackTrace();
            this.msj = "Error" + e.getMessage();
        }
        FacesMessage mensaje = new FacesMessage(this.msj);
        FacesContext.getCurrentInstance().addMessage(null, mensaje);
    }

    //Logica de Listar los registros de la base de datos
    public List<Curso> getLtsCurso() {
        return cursoFacade.findAll();
    }

    //Logica de conexion (ARREGLAR CODIGO)
    Connection con;

    public Connection getConnection() {

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/proyectoappweb", "root", "");
        } catch (Exception e) {
        }
        return con;
    }

    //Logica listar imagen
    public void listarImg(int id, HttpServletResponse response) {
        Connection con;
        PreparedStatement ps;
        ResultSet rs;
        String sql = "select * from curso where idcurso=" + id;
        InputStream inputStream = null;
        OutputStream outputStream = null;
        BufferedInputStream bufferedInputStream = null;
        BufferedOutputStream bufferedOutputStream = null;

        response.setContentType(
                "image/*");
        try {
            outputStream = response.getOutputStream();
            con = getConnection();
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            if (rs.next()) {
                inputStream = rs.getBinaryStream(3);
            }
            bufferedInputStream = new BufferedInputStream(inputStream);
            bufferedOutputStream = new BufferedOutputStream(outputStream);
            int i = 0;
            while ((i = bufferedInputStream.read()) != -1) {
                bufferedOutputStream.write(i);
            }
        } catch (Exception e) {
        }
    }

    //Logica Delete
    public void eliminar(Curso eliminar) {
        try {
            this.cursoFacade.remove(eliminar);
            this.msj = "Curso Eliminado Correctamente";

        } catch (Exception ex) {
            ex.printStackTrace();
            this.msj = "Error" + ex.getMessage();
        }
        FacesMessage mensaje = new FacesMessage(this.msj);
        FacesContext.getCurrentInstance().addMessage(null, mensaje);
    }

    public void actualizar() {
        try {
            this.cursoFacade.edit(curso);
            this.curso = new Curso();
            this.msj = "Actualizado Con exito";
        } catch (Exception e) {
            e.printStackTrace();
            this.msj = "Error : " + e.getMessage();
        }
        FacesMessage mens = new FacesMessage(this.msj);
        FacesContext.getCurrentInstance().addMessage(null, mens);
    }

    public void cargarID(Curso curso) {
        this.curso = curso;

    }

    public void limpiar() {
        this.curso = new Curso();
    }
}

src/java/managedBean/UsuarioBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedBean;

import entidades.Usuario;
import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import servicios.UsuarioFacadeLocal;

/**
 *
 * @author Saulinho-Laptop
 */
@Named(value = "usuarioBean")
@ViewScoped
public class UsuarioBean implements Serializable{

    @EJB
    private UsuarioFacadeLocal usuarioFacade;

    private Usuario usuario;

    @PostConstruct
    public void init() {
        usuario = new Usuario();
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public String iniciarSesion() {
        Usuario us;
        String redireccion = null;
        try {
            us = usuarioFacade.iniciarSesion(usuario);
            if (us != null) {     
                //Almacenar en la sesión de JSF
                FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("usuario", us);
                redireccion = "/jsfPrincipal?faces-redirect=true";
            } else {
                FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN, "Aviso", " Credenciales incorrectas"));
            }
        } catch (Exception e) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, "Aviso", "Error!"));
        }
        return redireccion;
    }
}

web/IniciarSession.xhtml
<!DOCTYPE html>
<html lang="en"
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <meta charset="utf-8" />
        <title>Web Application | todo</title>
        <link rel="stylesheet" href="Web Application _ todo_files/app.v2.css" type="text/css"/>
        <link rel="stylesheet" href="Web Application _ todo_files/font.css" type="text/css"/>
        <link href="css/landing-page.css" rel="stylesheet"/>
    </h:head>
    <h:body>

        <header class="masthead2">
            <section id="content" class="m-t-lg wrapper-md animated fadeInUp">
                <div class="row m-n">
                    <div class="col-md-4 col-md-offset-4 m-t-lg">
                        <section class="panel">
                            <header class="panel-heading text-center"> Sign in </header>
                            <h:form class="panel-body">
                                <p:messages autoUpdate="true" showDetail="true"/>
                                <div class="form-group"> <label class="control-label">Email</label> <p:inputText type="email" value="#{usuarioBean.usuario.email}" placeholder="testConnection@gmail.com" class="form-control"/>  </div>
                                <div class="form-group"> <label class="control-label">Password</label> <p:inputText type="password" value="#{usuarioBean.usuario.password}" placeholder="Password" class="form-control"/> </div>
                                <div class="checkbox"> <label> <input type="checkbox"/> Keep me logged in </label> </div>
                                <a href="#" class="pull-right m-t-xs"><small>Forgot password?</small></a> <p:commandButton value="Sign in" action="#{usuarioBean.iniciarSesion()}" class="btn btn-info"/>
                                <div class="line line-dashed"></div>
                                <a href="#" class="btn btn-facebook btn-block m-b-sm"><i class="fa fa-facebook pull-left"></i>Sign in with Facebook</a> <a href="#" class="btn btn-twitter btn-block"><i class="fa fa-twitter pull-left"></i>Sign in with Twitter</a> 
                                <div class="line line-dashed"></div>
                                <p class="text-muted text-center"><small>Do not have an account?</small></p>
                                <a href="jsfCrearUsuario.xhtml" class="btn btn-white btn-block">Create an account</a> 
                            </h:form>
                        </section>
                    </div>
                </div>
            </section>
            <!-- / footer --><script src="js/app.v2.js"></script> <!-- Bootstrap --> <!-- app --> 
        </header>
    </h:body>
</html>

web/amdCurso.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Registrar Cursos</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"/>
    </h:head>
    <h:body>
        <p:messages showDetail="true"/>
        <center>
            <h:form id="f" class="col-md-6"  enctype="multipart/form-data" >
                <div class="card">
                    <div class="card-header">
                        <h3>Registrar Cursos</h3>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label>ID</label>
                            <h:inputText value="#{cursoBean.curso.idCurso}" class="form-control"/>
                        </div>
                        <div class="form-group">
                            <label>Nombre del Curso</label>
                            <h:inputText value="#{cursoBean.curso.nombres}" required="true" class="form-control"/>
                        </div>
                        <div class="form-group">
                            <label>Foto</label>
                            <br/>
                            <p:growl showDetail="true"/>
                            <p:fileUpload value="#{cursoBean.file}" mode="simple"/>
                        </div>
                        <div class="form-group">
                            <label>Descripción</label>
                            <h:inputText value="#{cursoBean.curso.descripcion}" class="form-control"/>
                        </div>
                        <div class="form-group">
                            <label>Precio</label>
                            <h:inputText value="#{cursoBean.curso.precio}" class="form-control"/>
                        </div>
                        <div class="form-group">
                            <label>Stock</label>
                            <h:inputText value="#{cursoBean.curso.stock}" class="form-control"/>
                        </div>
                        <div class="form-group">
                            <label>Tiempo de duración</label>
                            <h:inputText value="#{cursoBean.curso.tiempoDeDuracion}" class="form-control"/>
                        </div>
                        <div class="form-group">
                            <label>Nombre del Profesor</label>
                            <h:inputText value="#{cursoBean.curso.nombredelprofesor}" class="form-control"/>
                        </div>
                        <div class="form-group">
                            <label>Requisitos</label>
                            <h:inputText value="#{cursoBean.curso.requisitos}" class="form-control"/>
                        </div>
                        <div class="form-group">
                            <label>Fecha de registro</label>
                            <p:inputText value="#{cursoBean.curso.fechaderegistro}" class="form-control">
                            <f:convertDateTime type="Date" pattern="dd/mm/yyyy"/>
                            </p:inputText>
                        </div>
                    </div>
                    <div class="card-footer">
                        <p:commandButton class="btn btn-outline-primary" value="Guardar" actionListener="#{cursoBean.insert()}"/> 
                        <p:commandButton class="btn btn-outline-primary" value="Actualizar" actionListener="#{cursoBean.actualizar()}"
                                         update=":f"/>   
                    </div>                
                </div>
            </h:form>
        </center>

        <div class="container mt-4">
            <div class="form-group">
                <table class="table table-hover">
                    <thead>
                        <tr class="text-center">
                            <th>ID</th>
                            <th>NOMBRES</th>
                            <th>IMAGEN</th>
                            <th>DESCIRPCION</th>
                            <th>PRECIO</th>
                            <th>STOCK</th>
                            <th>TIEMPO_DURACION</th>
                            <th>PROFESOR</th>
                            <th>REQUISITOS</th>
                            <th>FECHA_REGISTRO</th>
                            <th>ACCION</th>
                        </tr>
                    </thead>
                    <tbody>
                        <c:forEach var="p" items="${cursoBean.ltsCurso}">
                            <tr class="text-center">
                                <td>${p.idCurso}</td>
                                <td>${p.nombres}</td>
                                <td><img src="ControlerIMG?id=${p.idCurso}" width="100" height="100"/></td>
                                <td>${p.descripcion}</td>
                                <td>${p.precio}</td>
                                <td>${p.stock}</td>
                                <td>${p.tiempoDeDuracion}</td>
                                <td>${p.nombredelprofesor}</td>
                                <td>${p.requisitos}</td>
                                <td>${p.fechaderegistro}</td>
                                <h:form>
                                    <td>                          
                                        <p:commandButton icon="ui-icon-pencil" class="btn btn-warning" value="Editar" actionListener="#{cursoBean.cargarID(p)}" update=":f" />
                                        <p:commandButton icon="ui-icon-trash" class="btn btn-danger" value="Eliminar" actionListener="#{cursoBean.eliminar(p)}" />
                                    </td>
                                </h:form>
                            </tr>
                        </c:forEach>                    
                    </tbody>
                </table>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </h:body>
</html>

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <p:growl id="msj" />
        <h:form id="nuevo">
            <p:fieldset legend="Nuevo Coche" toggleable="true">
                <p:panelGrid columns="1">
                    <p:commandButton value="Nuevo Coche" oncomplete="PF('mostrar').show();" />
                </p:panelGrid>
            </p:fieldset>
        </h:form>
        <p:dialog widgetVar="mostrar" header="Datos" modal="true" showEffect="clip" resizable="false">
            <p:ajax event="close" listener="#{cursoBean.limpiar()}" update="valor" />
            <h:form id="valor">
                <p:panelGrid columns="2">
                    <p:outputLabel value="Ingrese ID" />
                    <p:inputText value="#{cursoBean.curso.idCurso}" />
                    <p:outputLabel value="Ingrese Color" />
                    <p:inputText value="#{cursoBean.curso.nombres}" />

                    <p:commandButton value="Guardar" actionListener="#{cursoBean.insert()}" 
                                     rendered="#{managedCoche.coche.id_coche == 0}"
                                     update=":Datos valor :msj" oncomplete="PF('mostrar').hide();" />
                    <p:commandButton value="Actualizar" actionListener="#{cursoBean.actualizar()}" 
                                     rendered="#{managedCoche.coche.id_coche != 0}"
                                     update=":Datos valor :msj" oncomplete="PF('mostrar').hide();" />
                </p:panelGrid>
            </h:form>
        </p:dialog>
        <h:form id="Datos">
            <p:fieldset legend="Datos Coches" toggleable="true">
                <p:dataTable value="#{cursoBean.ltsCurso}" var="c">
                    <p:column headerText="Id">
                        <h:outputText value="#{c.idCurso}" />
                    </p:column>
                    <p:column headerText="Modelo">
                        <h:outputText value="#{c.nombres}" />
                    </p:column>

                    <p:column headerText="Eliminar">
                        <p:commandButton value="Eliminar" actionListener="#{cursoBean.eliminar(c)}" 
                                         update=":msj" />
                    </p:column>
                    <p:column headerText="Actualizar">
                        <p:commandButton value="Actualizar" actionListener="#{cursoBean.cargarID(c)}" 
                                         oncomplete="PF('mostrar').show();" update=":valor" />
                    </p:column>
                </p:dataTable>
            </p:fieldset>
        </h:form>
    </h:body>
</html>


<div class="card">
    <div class="card-header">
        <h3>Registrar Cursos</h3>
    </div>
    <div class="card-body">
        <div class="form-group">
            <label>ID</label>
            <p:inputText value="#{cursoBean.curso.idCurso}" class="form-control" />
        </div>
        <div class="form-group">
            <label>NOMBRE</label>
            <p:inputText value="#{cursoBean.curso.nombres}" class="form-control" />
        </div>
        <div class="form-group">
            <label>Foto</label>
            <br/>
            <p:growl showDetail="true"/>
            <p:fileUpload value="#{cursoBean.file}" mode="simple"/>
        </div>
    </div>
</div>
<div class="card-footer">
    <p:commandButton class="btn btn-outline-primary" value="Guardar" actionListener="#{cursoBean.insert()}"/> 
    <p:commandButton class="btn btn-outline-primary" value="Actualizar" actionListener="#{cursoBean.actualizar()}"
                     update=":f"/>   
</div>   

web/jsfCrearUsuario.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <head>
        <title>Usuario Registro</title>
        <!-- Bootstrap core CSS -->
        <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>
        <!-- Custom fonts for this template -->
        <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet"/>
        <link href="vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css"/>
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css"/>

        <!-- Custom styles for this template -->
        <link href="css/landing-page.css" rel="stylesheet"/>

        <link rel="stylesheet" href="Web Application _ todo_files/app.v2.css" type="text/css"/>
        <link rel="stylesheet" href="Web Application _ todo_files/font.css" type="text/css"/>
    </head>

    <body>
        <header class="masthead2" >
            <section id="content" class="m-t-lg wrapper-md animated fadeInUp">
                <form style="background: #fff; max-width: 500px; min-height: 500px; margin: auto;border-radius: 5%;margin-top: 100px ">
                    <center>
                        <br></br>
                        <strong style="font: 45px Arial;color: #1A5276  ">Registrate</strong>
                        <br></br>
                        <br></br>

                        <div class="Registro">
                            <div class="input-Registro">
                                <input type="text" placeholder="Nombre Completo" style="font-size: 20px; width: 80%; padding: 10px; border: 1px solid #aaa;"/>
                            </div>
                            <br></br>

                            <div class="input-Registro">
                                <input type="email" placeholder="Correo Electrónico" style="font-size: 20px; width: 80%; padding: 10px; border: 1px solid #aaa;"/>
                            </div>
                            <br></br>

                            <div class="input-Registro">
                                <input type="password" placeholder="Contraseña" style="font-size: 20px; width: 80%; padding: 10px; border: 1px solid #aaa;"/>
                            </div>
                            <br></br>

                            <input type="checkbox" id="cbox1" value="aceptar_terminos"/> 
                            Aceptas nuestras Condiciones de uso y Política.
                            de privacidad
                            <br></br>
                            <br></br>

                            <div class="input-Registro">
                                <input type="submit" value="Registrate"  style="border: 1px solid #aaa;width: 80%;color: white;font-size: 20px;background:  #1A5276 ;
                                       padding: 15px 20px;border-radius: 5px;cursor: pointer;"/>
                            </div>
                            <br></br>
                            ¿Ya tienes cuenta? <a class="Link" href="IniciarSession.xhtml" style="text-decoration: none;color: #1A5276 ;
                                                  font-weight: 600;">Iniciar Sesion </a>
                        </div> 
                    </center>
                </form>
            </section>
        </header>
    </body>
</html>

web/jsfPrincipal.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <h:head>
        <title>Facelet Title</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous"/>

    </h:head>
    <h:body>
        <div class="card">
            <h:form>  
                <p:growl id="messages"/>
                <p:menubar>
                    <p:submenu label="Store" icon="pi pi-file">
                        <p:submenu label="New" icon="pi pi-briefcase">
                            <p:menuitem value="Project" url="#"/>
                            <p:menuitem value="Other" url="#"/>
                        </p:submenu>
                        <p:menuitem value="Open" url="#"/>

                        <p:menuitem value="Quit" url="#"/>
                    </p:submenu>

                    <p:submenu label="Home" icon="pi pi-pencil">
                        <p:menuitem value="Undo" url="#" icon="pi pi-angle-double-left"/>
                        <p:menuitem value="Redo" url="#" icon="pi pi-angle-double-right"/>
                    </p:submenu>



                    <p:submenu label="Ofertas del dia" icon="pi pi-cog">
                        <p:submenu label="Ajax" icon="pi pi-refresh">
                            <p:menuitem value="Save" action="#{menuView.save}" icon="pi pi-save" update="messages"/>
                            <p:menuitem value="Update" action="#{menuView.update}" icon="pi pi-refresh"
                                        update="messages"/>
                        </p:submenu>
                        <p:submenu label="Non-Ajax" icon="pi pi-clone">
                            <p:menuitem value="Delete" action="#{menuView.delete}" icon="pi pi-times" update="messages"
                                        ajax="false"/>
                        </p:submenu>
                    </p:submenu>

                    <p:menuitem value="Quit" url="http://www.primefaces.org" icon="pi pi-times"/>
                    
                    <p:submenu label="Carrito" icon="fa fa-cart-plus">
                    </p:submenu>
                    
                    


                    <f:facet name="options">
                        <p:inputText style="margin:1px 10px 1px 1px;" placeholder="Search"/>
                        <p:commandButton type="button" value="Logout" icon="pi pi-home"/>
                    </f:facet>
                </p:menubar>
            </h:form>
        </div>


        <div class="container mt-2">
            <div class="row">
                <c:forEach var="items" items="${cursoBean.ltsCurso}">
                    <div class="col-sm-4">
                        <div class="card">
                            <div class="card-header">
                                <h1>${items.nombres}</h1>
                            </div>
                            <div class="card-body">
                                <i>$.${items.precio}</i>
                                <td><img src="ControlerIMG?id=${items.idCurso}" width="200" height="180"/></td>
                            </div>
                            <div class="card-footer text-center">
                                <label>${items.descripcion}</label>
                                <div>
                                    <a href="" class="btn btn-outline-info">Agregar a Carrito</a>
                                    <a href="" class=" btn btn-danger">Comprar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </c:forEach>
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
                <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
            </div>
        </div>

    </h:body>
</html>

web/welcomePrimefaces.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>PrimeFaces</title>
            </f:facet>
        </h:head>

        <h:body>     
            <h:form>
                <p:messages autoUpdate="true" showDetail="true"/>
                <p:inputText value="#{usuarioBean.usuario.email}"/>
                <p:inputText value="#{usuarioBean.usuario.password}"/>
                <p:commandButton value="entar" action="#{usuarioBean.iniciarSesion()}"/>
            </h:form> 

        </h:body>


    </f:view>
</html>